import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PromoCompenent from "@/components/Main/PromoCompenent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <PromoCompenent />
        <main>
          <div className="container">
            {children}
          </div>
        </main>
        <Footer />

      </body>
    </html>
  );
}
